[package]
name = "cargo-lambda-macro"
version = "0.1.0"
edition = "2024"
authors = ["William Stoneham <william.stoneham04@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
