[package]
name = "cargo-lambda-macro"
version = "0.1.0"
edition = "2024"
authors = ["William Stoneham <william.stoneham04@gmail.com>"]

[dependencies]
lambda_macro = { path = "lambda_macro" }
payload = { path = "payload" }


[workspace]
members = ["lambda_macro", "payload"]
